### ISSUE TITLE
About docs at header of source file

### ISSUE THREAD

**Issue by songmeixu** [danpovey/k2#118]
I found that the first line is a relative path of each source file. Is it for any purpose? 

Now, I wanna change it to be doxygen friendly and change the dir organization. And keep the RELATIVE path is tedious and non-doxygen style as to me.

I suggest a new one below, though it may be a trivial thing. But I wanna ask guys firstly.
```cpp
/**
 * @file context.cu
 * @brief
 * Implement ...
 *
 * @copyright
 * Copyright (c)  2020  Name (email)					
 *
 * @copyright
 * See LICENSE for clarification regarding multiple authors
 */
```

**Comment by danpovey** [comment]
That change is fine with me.

**Comment by songmeixu** [comment]
close as no need new replay
