### ISSUE TITLE
Construct FSA from un-sorted list of arcs

### ISSUE THREAD

**Issue by danpovey** [danpovey/k2#31]
I realized that it will be convenient for certain algorithms if we can construct an FSA from vector of arcs that isn't sorted.  (So that version of the constructor would have to sort them, not necessarily using std::sort).  In addition, if we allow that constructor to accept input where the final-state is not numbered last, and have it topologically sort the input itself, it would be helpful; then algorithms like composition and determinization won't have to worry about renumbering states; and they can output big lists of arcs all at once. 

If it seems unnatural to implement this as a constructor, having it as a pointer output-arg to a function is fine.

Also, we should have a swap() or Swap() function in the Fsa type, which would call the vectors' swap functions.

**Comment by qindazhu** [comment]
I'll add swap tomorrow.

For composition, seems we can number the states when iterating over the queue, 
https://github.com/danpovey/k2/blob/master/k2/csrc/fsa_algo.cc#L332-L333
I have no idea about its necessity in determinization for now.

Anyway, if it would be added, I prefer to add the constructor as a function with output-arg.

**Comment by csukuangfj** [comment]
what if there is a cycle and the fsa cannot be topsorted? 

Abort?

**Comment by danpovey** [comment]
Firstly, we should have the top-sorting optional: we may sometimes want to just reorder the final-state so it's the last one.

I'd suggest to exit the program with a printed message if the user requested top-sorting and it couldn't be top-sorted.  But don't make that dependent on debug level.

**Comment by csukuangfj** [comment]
> we should have the top-sorting optional: we may sometimes want to just reorder the final-state so it's the last one.

what if the graph is not connected? In this case, how to determine which state is the final state?
