### ISSUE TITLE
Randomized testing

### ISSUE THREAD

**Issue by danpovey** [danpovey/k2#38]
It would be nice to have utilities for randomized testing.
I'm thinking of a mechanism of generating random FSAs.
We have something in Kaldi's fstext/ directory.  There could be an option for when it needs to be acyclic.

**Comment by csukuangfj** [comment]
I can implement it by following 
https://github.com/kaldi-asr/kaldi/blob/master/src/fstext/rand-fst.h

**Comment by danpovey** [comment]
Great!
