### ISSUE TITLE
Is there any convenient way to create alias of `indexes` and `data` in `Array2`？

### ISSUE THREAD

**Issue by qindazhu** [danpovey/k2#56]
As we will declare many classes (Fsa, AuxLabels, Cfsa, etc.) with `Array2`, wondering if there is any convenient way to create alias of `indexes` and `data` so that we can use those alias in functions to make code clear (otherwise we may create those alias in functions again and again)

For example (pseudo code)
```
using Fsa = Array2<Arc*, int32_t>
alias Fsa::arc_indexes = Fsa::indexes;
alias Fsa::arcs = Fsa::data;
```
One possible approach I thought of is wrapping `Array2` in a struct:
```
struct Fsa {
 Array2<Arc *, int32_t> m;
 Arc *&arcs = m.data;
 int32_t *&arc_indexes = m.indexes;
}；
```
(Two extra advantages of using struct here are that:
1.  Users cannot misuse class as another class that has the same template parameters in `Array2`, for example they can not pass Fsa to a function that accepts Cfsa where `Fsa =  Cfsa = Array2<Arc*, int32_t>`)
2. We can define extra methods in those structs, such as `NumStates()`, `FinalStates()`, `NumArcs`. Otherwise it seems we could just define those methods in Python code (and **cannot do this in C++ code**)?
)

**Comment by danpovey** [comment]
We resolved this via in-person discussion.   Will use the generic Array2
names like indexes and data, rather than Fsa-specific notation.

**Comment by qindazhu** [comment]
Sure, and will add `IndexT size2` in `Array2` as the total number of elements in `data` (from indexes[0] to indexes[size])
