### ISSUE TITLE
Template for contexts

### ISSUE THREAD

**Issue by danpovey** [danpovey/k2#72]
Can someone please write a template that works for an arbitrary list of objects of possibly different types,
and does this:
```
ContextPtr GetContext(S &s, T &t, U &u, ..) {
   ContextPtr ans1 = s.Context(),  ans2 = GetContext(t, u, ..);
   assert(*ans1 == *ans2 && "Contexts mismatch");
   return ans1;  
}
```
You can make a PR to my cuda_draft branch, e.g. in context.h, although of course that branch doesn't compile.

**Comment by danpovey** [comment]
... BTW, that "assert" should really be something that happens in non-debug mode as well, since it could be caused
by user code.  We'll have to decide on a mechanism for raising errors like this.  Perhaps raising an exception?  Might
be easier in the context of code called from Python.

**Comment by qindazhu** [comment]
OK, will do, maybe later today.

**Comment by qindazhu** [comment]
Will close this issue as we have implemented the function with PR https://github.com/danpovey/k2/pull/73
