### ISSUE TITLE
where do I find _k2 module

### ISSUE THREAD

**Issue by xin-w8023** [danpovey/k2#81]
I made the project, but couldn't find the module `_k2`, or is that an extended library?

**Comment by csukuangfj** [comment]
You can find it in `build/lib` with the name `_k2.so`.

To use it, you can do the following

```bash
git clone https://github.com/danpovey/k2.git
mkdir k2/build
cd k2/build
cmake ..
make

cd ..
export PYTHONPATH=$PWD/build/lib:$PWD/k2/python

python3 -c "import _k2; print(_k2.__doc__)"
```

`k2` is preferred over `_k2`.  So normally you would use

```python3
import k2
```

<https://github.com/danpovey/k2/tree/master/k2/python/tests> is a good place for learning how to use k2 in Python.

**Comment by xin-w8023** [comment]
> You can find it in `build/lib` with the name `_k2.so`.
> 
> To use it, you can do the following
> 
> ```shell
> git clone https://github.com/danpovey/k2.git
> mkdir k2/build
> cd k2/build
> cmake ..
> make
> 
> cd ..
> export PYTHONPATH=$PWD/build/lib:$PWD/k2/python:$PYTHONPATH
> 
> python3 -c "import _k2; print(_k2.__doc__)"
> ```
> 
> `k2` is preferred over `_k2`. So normally you would use
> 
> ```python
> import k2
> ```
> 
> https://github.com/danpovey/k2/tree/master/k2/python/tests is a good place for learning how to use k2 in Python.

thanks a lot, it works.
