### ISSUE TITLE
A compile error of k2/k2/csrc/cuda/ops_test.cu

### ISSUE THREAD

**Issue by Jarvan-Wang** [danpovey/k2#96]
OS version is Linux 3.10.0-957.el7.x86_64
nvcc is 10.2
gcc is 6.3.1

Error is here:
`<pre>[ 94%] <font color="#4E9A06">Building CUDA object k2/csrc/cuda/CMakeFiles/ops_test.dir/ops_test.cu.o</font>
cd /search/odin/wangjiawen/k2/build/k2/csrc/cuda &amp;&amp; /usr/local/cuda-10.2/bin/nvcc -forward-unknown-to-host-compiler -DGOOGLE_GLOG_DLL_DECL=&quot;&quot; -DGOOGLE_GLOG_DLL_DECL_FOR_UNITTESTS=&quot;&quot; -I/search/odin/wangjiawen/k2 -I/search/odin/wangjiawen/k2/build/_deps/cub-src -I/search/odin/wangjiawen/k2/build/_deps/glog_glog-build -I/search/odin/wangjiawen/k2/build/_deps/glog_glog-src/src -I/search/odin/wangjiawen/k2/build/_deps/googletest-src/googlemock/include -isystem=/search/odin/wangjiawen/k2/build/_deps/googletest-src/googletest/include -isystem=/search/odin/wangjiawen/k2/build/_deps/googletest-src/googletest --expt-extended-lambda -gencode arch=compute_30,code=sm_30 --expt-extended-lambda -gencode arch=compute_32,code=sm_32 --expt-extended-lambda -gencode arch=compute_35,code=sm_35 --expt-extended-lambda -gencode arch=compute_50,code=sm_50 --expt-extended-lambda -gencode arch=compute_52,code=sm_52 --expt-extended-lambda -gencode arch=compute_53,code=sm_53 --expt-extended-lambda -gencode arch=compute_60,code=sm_60 --expt-extended-lambda -gencode arch=compute_61,code=sm_61 --expt-extended-lambda -gencode arch=compute_62,code=sm_62 --expt-extended-lambda -gencode arch=compute_70,code=sm_70 --expt-extended-lambda -gencode arch=compute_72,code=sm_72 -g -std=c++14 -x cu -c /search/odin/wangjiawen/k2/k2/csrc/cuda/ops_test.cu -o CMakeFiles/ops_test.dir/ops_test.cu.o
/search/odin/wangjiawen/k2/k2/csrc/cuda/ops.h(79): error: class &quot;std::shared_ptr&lt;k2::Context&gt;&quot; has no member &quot;IsCompatible&quot;
          detected during instantiation of &quot;void k2::GpuTransposeTest&lt;T&gt;(int32_t, int32_t, int32_t, __nv_bool) [with T=int32_t]&quot; 
/search/odin/wangjiawen/k2/k2/csrc/cuda/ops_test.cu(80): here

/search/odin/wangjiawen/k2/k2/csrc/cuda/ops.h(80): error: class &quot;std::shared_ptr&lt;k2::Context&gt;&quot; has no member &quot;IsCompatible&quot;
          detected during instantiation of &quot;void k2::GpuTransposeTest&lt;T&gt;(int32_t, int32_t, int32_t, __nv_bool) [with T=int32_t]&quot; 
/search/odin/wangjiawen/k2/k2/csrc/cuda/ops_test.cu(80): here</pre>`

which cause by:
`template <typename T>
void Transpose(ContextPtr &c, const Array2<T> &src, Array2<T> *dest) {
  assert(c.IsCompatible(src.Context()));
  assert(c.IsCompatible(dest->Context()));
  //...
`
the c is get by std::make_shared<CudaContext>
as i known, this syntax is supported by c++11 and above
and i passed -std=c++14 to nvcc, so, its weird..

**Comment by danpovey** [comment]
Ah, should be c->IsCompatible().  You can make a PR if you want.  Just be
aware, we will likely change the license from Apache->MIT (they are very
similar), so make sure you're OK with that.

**Comment by danpovey** [comment]
forget the MIT thing, looks like it already is.

**Comment by qindazhu** [comment]
It's weird that the code can be compiled successfully on my machine (`gcc (GCC) 4.8.5` and `nvcc  release 10.0`)..
@danpovey maybe we should update gcc version on Xiaomi cluster.

**Comment by danpovey** [comment]
Probably it was a template that was never instantiated, different compilers
handle that differently.

**Comment by qindazhu** [comment]
No, it has been instantiated in ops_test.cu..that's really strange. The current code in `cuda_draft` can be compiler and run successfully on Xiaomi cluster.
